// Generated by CoffeeScript 1.5.0
var City;

City = (function() {

  function City() {}

  City.prototype.mayor = 'Jasper Kennis';

  City.prototype.inhabitants = 0;

  City.prototype.funds = 10000;

  return City;

})();
