// Generated by CoffeeScript 1.4.0
var Controller;

Controller = (function() {

  function Controller() {
    this.bind();
  }

  Controller.prototype.bind = function() {
    window.onkeyup = this.keyUp;
    return window.onkeydown = this.keyDown;
  };

  Controller.prototype.keyUp = function(e) {
    switch (e.keyCode) {
      case 38:
        return this.gameSignals.keyUp.up.dispatch();
      case 40:
        return this.gameSignals.keyUp.down.dispatch();
      case 37:
        return this.gameSignals.keyUp.left.dispatch();
      case 39:
        return this.gameSignals.keyUp.right.dispatch();
    }
  };

  Controller.prototype.keyDown = function(e) {
    switch (e.keyCode) {
      case 38:
        return this.gameSignals.keyDown.up.dispatch();
      case 40:
        return this.gameSignals.keyDown.down.dispatch();
      case 37:
        return this.gameSignals.keyDown.left.dispatch();
      case 39:
        return this.gameSignals.keyDown.right.dispatch();
    }
  };

  return Controller;

})();
