// Generated by CoffeeScript 1.4.0
var Grid,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Grid = (function(_super) {

  __extends(Grid, _super);

  Grid.prototype.tiles = [];

  function Grid(rows, cols) {
    this.rows = rows != null ? rows : 100;
    this.cols = cols != null ? cols : 100;
    this.drawTiles();
  }

  Grid.prototype.drawTiles = function() {
    var col, row, tile, _i, _ref, _results;
    _results = [];
    for (row = _i = _ref = this.rows - 1; _ref <= 0 ? _i <= 0 : _i >= 0; row = _ref <= 0 ? ++_i : --_i) {
      _results.push((function() {
        var _j, _ref1, _results1;
        _results1 = [];
        for (col = _j = _ref1 = this.cols - 1; _ref1 <= 0 ? _j <= 0 : _j >= 0; col = _ref1 <= 0 ? ++_j : --_j) {
          _results1.push(tile = new Tile(row, col));
        }
        return _results1;
      }).call(this));
    }
    return _results;
  };

  return Grid;

})(Base);
