// Generated by CoffeeScript 1.5.0
var Sand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Sand = (function(_super) {

  __extends(Sand, _super);

  function Sand() {
    Sand.__super__.constructor.apply(this, arguments);
  }

  Sand.prototype.color = 'yellow';

  return Sand;

})(Tile);
